
### Create user
POST http://localhost:8080/user
Content-type: application/json

{
  ...
}
### Update entity
PUT http://localhost:8080/entity/1
Content-type: application/json

{
  ...
}

### Fetch entities
GET http://localhost:8080/entity
Content-type: application/json

### Fetch entity
GET http://localhost:8080/entity/1
Content-type: application/json

### Delete entity
DELETE http://localhost:8080/entity/1
