### Api-gateway config
GET http://localhost:8080/configs
Content-type: application/json

{
    "property": "HelloWorld4458888888",
    "value": "1"
}

### Service (instance 1) configs
GET http://localhost:8081/configs
Content-type: application/json

{
    "property": "HelloWorld50008888888",
    "value": "HelloWorld60008888888888"
}

### Service (instance 2) configs
GET http://localhost:8082/configs
Content-type: application/json

{
    "property": "HelloWorld50008888888",
    "value": "HelloWorld60008888888888"
}

### Gateway Config refresh
POST http://localhost:8080/actuator/refresh

### Client Config refresh
POST http://localhost:8081/actuator/refresh

### Bus refresh
POST http://localhost:8080/actuator/bus-refresh

### Gateway configs in config server
GET http://localhost:8888/gateway/default
Content-type: application/json

{
    "name": "gateway",
    "profiles": [
        "default"
    ],
    "label": null,
    "version": "ec471ff5f393f9e73160ab5a28f8a78029dfdd3c",
    "state": null,
    "propertySources": [
        {
            "name": "file://config/gateway.properties",
            "source": {
                "some.value": "1"
            }
        },
        {
            "name": "file://config/application.properties",
            "source": {
                "management.endpoints.web.exposure.include": "bus-refresh,refresh,bus-env",
                "spring.rabbitmq.host": "rabbit",
                "spring.rabbitmq.port": "5672",
                "spring.rabbitmq.username": "guest",
                "spring.rabbitmq.password": "guest"
            }
        }
    ]
}

### Client configs in config server
GET http://localhost:8888/client/default
Content-type: application/json